name: newbie_android_app
description: A new Flutter project for Doubao API.
publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_markdown: ^0.6.14
  permission_handler: ^11.0.0
  image_gallery_saver: ^2.0.2
  path_provider: ^2.1.0
  device_info_plus: ^10.0.0
  image_picker: ^1.1.2
  mime: ^1.0.4
  video_player: ^2.10.1
  chewie: ^1.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
